.PHONY: clean All

All:
	@echo "----------Building project:[ serverchat - Debug ]----------"
	@cd "serverchat" && "$(MAKE)" -f  "serverchat.mk"
clean:
	@echo "----------Cleaning project:[ serverchat - Debug ]----------"
	@cd "serverchat" && "$(MAKE)" -f  "serverchat.mk" clean
