.PHONY: clean All

All:
	@echo "----------Building project:[ clientrefine - Debug ]----------"
	@cd "clientrefine" && "$(MAKE)" -f  "clientrefine.mk"
clean:
	@echo "----------Cleaning project:[ clientrefine - Debug ]----------"
	@cd "clientrefine" && "$(MAKE)" -f  "clientrefine.mk" clean
